### PR TITLE
Feature/#12recommended users

### PR DESCRIPTION
**Pull request by flxtagi**
Reccomended Users for current user Screen. Client side data fetching for now? maybe we change that to Server side fetching or with API route?

### CODE REVIEW

**Comment by rudigier** [comment]
Deploy is failing. Because there are some TS errors.

**Comment by rudigier** [comment]
Bitte noch die Fehler beheben und unsere API verwenden.

**Comment by flxtagi** [comment]
I was trying to that one clientside rendering but somehow not manage to do that. no luck! 😿 
 Propose now a working client-side rendering and we can do and test a preloader component (missing anyway) or do it SSR later.

**Review by rudigier — APPROVED** [review]
Ok for now that we can proceed. But all the User Infos shouldn't be in a client side API.

**Pull request merged**
